// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: toplevel.proto

package sizzle.types;

public final class Toplevel {
  private Toplevel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProjectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required string url = 2;
    boolean hasUrl();
    String getUrl();
    
    // repeated .sizzle.types.CodeRepository code_repositories = 3;
    java.util.List<sizzle.types.Code.CodeRepository> 
        getCodeRepositoriesList();
    sizzle.types.Code.CodeRepository getCodeRepositories(int index);
    int getCodeRepositoriesCount();
    java.util.List<? extends sizzle.types.Code.CodeRepositoryOrBuilder> 
        getCodeRepositoriesOrBuilderList();
    sizzle.types.Code.CodeRepositoryOrBuilder getCodeRepositoriesOrBuilder(
        int index);
    
    // repeated .sizzle.types.BugRepository bug_repositories = 4;
    java.util.List<sizzle.types.Bugs.BugRepository> 
        getBugRepositoriesList();
    sizzle.types.Bugs.BugRepository getBugRepositories(int index);
    int getBugRepositoriesCount();
    java.util.List<? extends sizzle.types.Bugs.BugRepositoryOrBuilder> 
        getBugRepositoriesOrBuilderList();
    sizzle.types.Bugs.BugRepositoryOrBuilder getBugRepositoriesOrBuilder(
        int index);
  }
  public static final class Project extends
      com.google.protobuf.GeneratedMessage
      implements ProjectOrBuilder {
    // Use Project.newBuilder() to construct.
    private Project(Builder builder) {
      super(builder);
    }
    private Project(boolean noInit) {}
    
    private static final Project defaultInstance;
    public static Project getDefaultInstance() {
      return defaultInstance;
    }
    
    public Project getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sizzle.types.Toplevel.internal_static_sizzle_types_Project_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sizzle.types.Toplevel.internal_static_sizzle_types_Project_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string url = 2;
    public static final int URL_FIELD_NUMBER = 2;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .sizzle.types.CodeRepository code_repositories = 3;
    public static final int CODE_REPOSITORIES_FIELD_NUMBER = 3;
    private java.util.List<sizzle.types.Code.CodeRepository> codeRepositories_;
    public java.util.List<sizzle.types.Code.CodeRepository> getCodeRepositoriesList() {
      return codeRepositories_;
    }
    public java.util.List<? extends sizzle.types.Code.CodeRepositoryOrBuilder> 
        getCodeRepositoriesOrBuilderList() {
      return codeRepositories_;
    }
    public int getCodeRepositoriesCount() {
      return codeRepositories_.size();
    }
    public sizzle.types.Code.CodeRepository getCodeRepositories(int index) {
      return codeRepositories_.get(index);
    }
    public sizzle.types.Code.CodeRepositoryOrBuilder getCodeRepositoriesOrBuilder(
        int index) {
      return codeRepositories_.get(index);
    }
    
    // repeated .sizzle.types.BugRepository bug_repositories = 4;
    public static final int BUG_REPOSITORIES_FIELD_NUMBER = 4;
    private java.util.List<sizzle.types.Bugs.BugRepository> bugRepositories_;
    public java.util.List<sizzle.types.Bugs.BugRepository> getBugRepositoriesList() {
      return bugRepositories_;
    }
    public java.util.List<? extends sizzle.types.Bugs.BugRepositoryOrBuilder> 
        getBugRepositoriesOrBuilderList() {
      return bugRepositories_;
    }
    public int getBugRepositoriesCount() {
      return bugRepositories_.size();
    }
    public sizzle.types.Bugs.BugRepository getBugRepositories(int index) {
      return bugRepositories_.get(index);
    }
    public sizzle.types.Bugs.BugRepositoryOrBuilder getBugRepositoriesOrBuilder(
        int index) {
      return bugRepositories_.get(index);
    }
    
    private void initFields() {
      name_ = "";
      url_ = "";
      codeRepositories_ = java.util.Collections.emptyList();
      bugRepositories_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getCodeRepositoriesCount(); i++) {
        if (!getCodeRepositories(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getBugRepositoriesCount(); i++) {
        if (!getBugRepositories(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUrlBytes());
      }
      for (int i = 0; i < codeRepositories_.size(); i++) {
        output.writeMessage(3, codeRepositories_.get(i));
      }
      for (int i = 0; i < bugRepositories_.size(); i++) {
        output.writeMessage(4, bugRepositories_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUrlBytes());
      }
      for (int i = 0; i < codeRepositories_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, codeRepositories_.get(i));
      }
      for (int i = 0; i < bugRepositories_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, bugRepositories_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sizzle.types.Toplevel.Project parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.Toplevel.Project parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Toplevel.Project parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sizzle.types.Toplevel.Project parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Toplevel.Project parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.Toplevel.Project parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sizzle.types.Toplevel.Project parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sizzle.types.Toplevel.Project parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sizzle.types.Toplevel.Project parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sizzle.types.Toplevel.Project parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sizzle.types.Toplevel.Project prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sizzle.types.Toplevel.ProjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sizzle.types.Toplevel.internal_static_sizzle_types_Project_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sizzle.types.Toplevel.internal_static_sizzle_types_Project_fieldAccessorTable;
      }
      
      // Construct using sizzle.types.Toplevel.Project.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCodeRepositoriesFieldBuilder();
          getBugRepositoriesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (codeRepositoriesBuilder_ == null) {
          codeRepositories_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          codeRepositoriesBuilder_.clear();
        }
        if (bugRepositoriesBuilder_ == null) {
          bugRepositories_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          bugRepositoriesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sizzle.types.Toplevel.Project.getDescriptor();
      }
      
      public sizzle.types.Toplevel.Project getDefaultInstanceForType() {
        return sizzle.types.Toplevel.Project.getDefaultInstance();
      }
      
      public sizzle.types.Toplevel.Project build() {
        sizzle.types.Toplevel.Project result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sizzle.types.Toplevel.Project buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sizzle.types.Toplevel.Project result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sizzle.types.Toplevel.Project buildPartial() {
        sizzle.types.Toplevel.Project result = new sizzle.types.Toplevel.Project(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.url_ = url_;
        if (codeRepositoriesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            codeRepositories_ = java.util.Collections.unmodifiableList(codeRepositories_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.codeRepositories_ = codeRepositories_;
        } else {
          result.codeRepositories_ = codeRepositoriesBuilder_.build();
        }
        if (bugRepositoriesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            bugRepositories_ = java.util.Collections.unmodifiableList(bugRepositories_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.bugRepositories_ = bugRepositories_;
        } else {
          result.bugRepositories_ = bugRepositoriesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sizzle.types.Toplevel.Project) {
          return mergeFrom((sizzle.types.Toplevel.Project)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sizzle.types.Toplevel.Project other) {
        if (other == sizzle.types.Toplevel.Project.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (codeRepositoriesBuilder_ == null) {
          if (!other.codeRepositories_.isEmpty()) {
            if (codeRepositories_.isEmpty()) {
              codeRepositories_ = other.codeRepositories_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureCodeRepositoriesIsMutable();
              codeRepositories_.addAll(other.codeRepositories_);
            }
            onChanged();
          }
        } else {
          if (!other.codeRepositories_.isEmpty()) {
            if (codeRepositoriesBuilder_.isEmpty()) {
              codeRepositoriesBuilder_.dispose();
              codeRepositoriesBuilder_ = null;
              codeRepositories_ = other.codeRepositories_;
              bitField0_ = (bitField0_ & ~0x00000004);
              codeRepositoriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCodeRepositoriesFieldBuilder() : null;
            } else {
              codeRepositoriesBuilder_.addAllMessages(other.codeRepositories_);
            }
          }
        }
        if (bugRepositoriesBuilder_ == null) {
          if (!other.bugRepositories_.isEmpty()) {
            if (bugRepositories_.isEmpty()) {
              bugRepositories_ = other.bugRepositories_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureBugRepositoriesIsMutable();
              bugRepositories_.addAll(other.bugRepositories_);
            }
            onChanged();
          }
        } else {
          if (!other.bugRepositories_.isEmpty()) {
            if (bugRepositoriesBuilder_.isEmpty()) {
              bugRepositoriesBuilder_.dispose();
              bugRepositoriesBuilder_ = null;
              bugRepositories_ = other.bugRepositories_;
              bitField0_ = (bitField0_ & ~0x00000008);
              bugRepositoriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBugRepositoriesFieldBuilder() : null;
            } else {
              bugRepositoriesBuilder_.addAllMessages(other.bugRepositories_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasUrl()) {
          
          return false;
        }
        for (int i = 0; i < getCodeRepositoriesCount(); i++) {
          if (!getCodeRepositories(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getBugRepositoriesCount(); i++) {
          if (!getBugRepositories(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              url_ = input.readBytes();
              break;
            }
            case 26: {
              sizzle.types.Code.CodeRepository.Builder subBuilder = sizzle.types.Code.CodeRepository.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addCodeRepositories(subBuilder.buildPartial());
              break;
            }
            case 34: {
              sizzle.types.Bugs.BugRepository.Builder subBuilder = sizzle.types.Bugs.BugRepository.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addBugRepositories(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required string url = 2;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        url_ = value;
        onChanged();
      }
      
      // repeated .sizzle.types.CodeRepository code_repositories = 3;
      private java.util.List<sizzle.types.Code.CodeRepository> codeRepositories_ =
        java.util.Collections.emptyList();
      private void ensureCodeRepositoriesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          codeRepositories_ = new java.util.ArrayList<sizzle.types.Code.CodeRepository>(codeRepositories_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          sizzle.types.Code.CodeRepository, sizzle.types.Code.CodeRepository.Builder, sizzle.types.Code.CodeRepositoryOrBuilder> codeRepositoriesBuilder_;
      
      public java.util.List<sizzle.types.Code.CodeRepository> getCodeRepositoriesList() {
        if (codeRepositoriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(codeRepositories_);
        } else {
          return codeRepositoriesBuilder_.getMessageList();
        }
      }
      public int getCodeRepositoriesCount() {
        if (codeRepositoriesBuilder_ == null) {
          return codeRepositories_.size();
        } else {
          return codeRepositoriesBuilder_.getCount();
        }
      }
      public sizzle.types.Code.CodeRepository getCodeRepositories(int index) {
        if (codeRepositoriesBuilder_ == null) {
          return codeRepositories_.get(index);
        } else {
          return codeRepositoriesBuilder_.getMessage(index);
        }
      }
      public Builder setCodeRepositories(
          int index, sizzle.types.Code.CodeRepository value) {
        if (codeRepositoriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCodeRepositoriesIsMutable();
          codeRepositories_.set(index, value);
          onChanged();
        } else {
          codeRepositoriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setCodeRepositories(
          int index, sizzle.types.Code.CodeRepository.Builder builderForValue) {
        if (codeRepositoriesBuilder_ == null) {
          ensureCodeRepositoriesIsMutable();
          codeRepositories_.set(index, builderForValue.build());
          onChanged();
        } else {
          codeRepositoriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addCodeRepositories(sizzle.types.Code.CodeRepository value) {
        if (codeRepositoriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCodeRepositoriesIsMutable();
          codeRepositories_.add(value);
          onChanged();
        } else {
          codeRepositoriesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addCodeRepositories(
          int index, sizzle.types.Code.CodeRepository value) {
        if (codeRepositoriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCodeRepositoriesIsMutable();
          codeRepositories_.add(index, value);
          onChanged();
        } else {
          codeRepositoriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addCodeRepositories(
          sizzle.types.Code.CodeRepository.Builder builderForValue) {
        if (codeRepositoriesBuilder_ == null) {
          ensureCodeRepositoriesIsMutable();
          codeRepositories_.add(builderForValue.build());
          onChanged();
        } else {
          codeRepositoriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addCodeRepositories(
          int index, sizzle.types.Code.CodeRepository.Builder builderForValue) {
        if (codeRepositoriesBuilder_ == null) {
          ensureCodeRepositoriesIsMutable();
          codeRepositories_.add(index, builderForValue.build());
          onChanged();
        } else {
          codeRepositoriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllCodeRepositories(
          java.lang.Iterable<? extends sizzle.types.Code.CodeRepository> values) {
        if (codeRepositoriesBuilder_ == null) {
          ensureCodeRepositoriesIsMutable();
          super.addAll(values, codeRepositories_);
          onChanged();
        } else {
          codeRepositoriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearCodeRepositories() {
        if (codeRepositoriesBuilder_ == null) {
          codeRepositories_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          codeRepositoriesBuilder_.clear();
        }
        return this;
      }
      public Builder removeCodeRepositories(int index) {
        if (codeRepositoriesBuilder_ == null) {
          ensureCodeRepositoriesIsMutable();
          codeRepositories_.remove(index);
          onChanged();
        } else {
          codeRepositoriesBuilder_.remove(index);
        }
        return this;
      }
      public sizzle.types.Code.CodeRepository.Builder getCodeRepositoriesBuilder(
          int index) {
        return getCodeRepositoriesFieldBuilder().getBuilder(index);
      }
      public sizzle.types.Code.CodeRepositoryOrBuilder getCodeRepositoriesOrBuilder(
          int index) {
        if (codeRepositoriesBuilder_ == null) {
          return codeRepositories_.get(index);  } else {
          return codeRepositoriesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends sizzle.types.Code.CodeRepositoryOrBuilder> 
           getCodeRepositoriesOrBuilderList() {
        if (codeRepositoriesBuilder_ != null) {
          return codeRepositoriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(codeRepositories_);
        }
      }
      public sizzle.types.Code.CodeRepository.Builder addCodeRepositoriesBuilder() {
        return getCodeRepositoriesFieldBuilder().addBuilder(
            sizzle.types.Code.CodeRepository.getDefaultInstance());
      }
      public sizzle.types.Code.CodeRepository.Builder addCodeRepositoriesBuilder(
          int index) {
        return getCodeRepositoriesFieldBuilder().addBuilder(
            index, sizzle.types.Code.CodeRepository.getDefaultInstance());
      }
      public java.util.List<sizzle.types.Code.CodeRepository.Builder> 
           getCodeRepositoriesBuilderList() {
        return getCodeRepositoriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          sizzle.types.Code.CodeRepository, sizzle.types.Code.CodeRepository.Builder, sizzle.types.Code.CodeRepositoryOrBuilder> 
          getCodeRepositoriesFieldBuilder() {
        if (codeRepositoriesBuilder_ == null) {
          codeRepositoriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              sizzle.types.Code.CodeRepository, sizzle.types.Code.CodeRepository.Builder, sizzle.types.Code.CodeRepositoryOrBuilder>(
                  codeRepositories_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          codeRepositories_ = null;
        }
        return codeRepositoriesBuilder_;
      }
      
      // repeated .sizzle.types.BugRepository bug_repositories = 4;
      private java.util.List<sizzle.types.Bugs.BugRepository> bugRepositories_ =
        java.util.Collections.emptyList();
      private void ensureBugRepositoriesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          bugRepositories_ = new java.util.ArrayList<sizzle.types.Bugs.BugRepository>(bugRepositories_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          sizzle.types.Bugs.BugRepository, sizzle.types.Bugs.BugRepository.Builder, sizzle.types.Bugs.BugRepositoryOrBuilder> bugRepositoriesBuilder_;
      
      public java.util.List<sizzle.types.Bugs.BugRepository> getBugRepositoriesList() {
        if (bugRepositoriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bugRepositories_);
        } else {
          return bugRepositoriesBuilder_.getMessageList();
        }
      }
      public int getBugRepositoriesCount() {
        if (bugRepositoriesBuilder_ == null) {
          return bugRepositories_.size();
        } else {
          return bugRepositoriesBuilder_.getCount();
        }
      }
      public sizzle.types.Bugs.BugRepository getBugRepositories(int index) {
        if (bugRepositoriesBuilder_ == null) {
          return bugRepositories_.get(index);
        } else {
          return bugRepositoriesBuilder_.getMessage(index);
        }
      }
      public Builder setBugRepositories(
          int index, sizzle.types.Bugs.BugRepository value) {
        if (bugRepositoriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBugRepositoriesIsMutable();
          bugRepositories_.set(index, value);
          onChanged();
        } else {
          bugRepositoriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setBugRepositories(
          int index, sizzle.types.Bugs.BugRepository.Builder builderForValue) {
        if (bugRepositoriesBuilder_ == null) {
          ensureBugRepositoriesIsMutable();
          bugRepositories_.set(index, builderForValue.build());
          onChanged();
        } else {
          bugRepositoriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addBugRepositories(sizzle.types.Bugs.BugRepository value) {
        if (bugRepositoriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBugRepositoriesIsMutable();
          bugRepositories_.add(value);
          onChanged();
        } else {
          bugRepositoriesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addBugRepositories(
          int index, sizzle.types.Bugs.BugRepository value) {
        if (bugRepositoriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBugRepositoriesIsMutable();
          bugRepositories_.add(index, value);
          onChanged();
        } else {
          bugRepositoriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addBugRepositories(
          sizzle.types.Bugs.BugRepository.Builder builderForValue) {
        if (bugRepositoriesBuilder_ == null) {
          ensureBugRepositoriesIsMutable();
          bugRepositories_.add(builderForValue.build());
          onChanged();
        } else {
          bugRepositoriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addBugRepositories(
          int index, sizzle.types.Bugs.BugRepository.Builder builderForValue) {
        if (bugRepositoriesBuilder_ == null) {
          ensureBugRepositoriesIsMutable();
          bugRepositories_.add(index, builderForValue.build());
          onChanged();
        } else {
          bugRepositoriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllBugRepositories(
          java.lang.Iterable<? extends sizzle.types.Bugs.BugRepository> values) {
        if (bugRepositoriesBuilder_ == null) {
          ensureBugRepositoriesIsMutable();
          super.addAll(values, bugRepositories_);
          onChanged();
        } else {
          bugRepositoriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearBugRepositories() {
        if (bugRepositoriesBuilder_ == null) {
          bugRepositories_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          bugRepositoriesBuilder_.clear();
        }
        return this;
      }
      public Builder removeBugRepositories(int index) {
        if (bugRepositoriesBuilder_ == null) {
          ensureBugRepositoriesIsMutable();
          bugRepositories_.remove(index);
          onChanged();
        } else {
          bugRepositoriesBuilder_.remove(index);
        }
        return this;
      }
      public sizzle.types.Bugs.BugRepository.Builder getBugRepositoriesBuilder(
          int index) {
        return getBugRepositoriesFieldBuilder().getBuilder(index);
      }
      public sizzle.types.Bugs.BugRepositoryOrBuilder getBugRepositoriesOrBuilder(
          int index) {
        if (bugRepositoriesBuilder_ == null) {
          return bugRepositories_.get(index);  } else {
          return bugRepositoriesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends sizzle.types.Bugs.BugRepositoryOrBuilder> 
           getBugRepositoriesOrBuilderList() {
        if (bugRepositoriesBuilder_ != null) {
          return bugRepositoriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bugRepositories_);
        }
      }
      public sizzle.types.Bugs.BugRepository.Builder addBugRepositoriesBuilder() {
        return getBugRepositoriesFieldBuilder().addBuilder(
            sizzle.types.Bugs.BugRepository.getDefaultInstance());
      }
      public sizzle.types.Bugs.BugRepository.Builder addBugRepositoriesBuilder(
          int index) {
        return getBugRepositoriesFieldBuilder().addBuilder(
            index, sizzle.types.Bugs.BugRepository.getDefaultInstance());
      }
      public java.util.List<sizzle.types.Bugs.BugRepository.Builder> 
           getBugRepositoriesBuilderList() {
        return getBugRepositoriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          sizzle.types.Bugs.BugRepository, sizzle.types.Bugs.BugRepository.Builder, sizzle.types.Bugs.BugRepositoryOrBuilder> 
          getBugRepositoriesFieldBuilder() {
        if (bugRepositoriesBuilder_ == null) {
          bugRepositoriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              sizzle.types.Bugs.BugRepository, sizzle.types.Bugs.BugRepository.Builder, sizzle.types.Bugs.BugRepositoryOrBuilder>(
                  bugRepositories_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          bugRepositories_ = null;
        }
        return bugRepositoriesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:sizzle.types.Project)
    }
    
    static {
      defaultInstance = new Project(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sizzle.types.Project)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sizzle_types_Project_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sizzle_types_Project_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016toplevel.proto\022\014sizzle.types\032\ncode.pro" +
      "to\032\nbugs.proto\"\224\001\n\007Project\022\014\n\004name\030\001 \002(\t" +
      "\022\013\n\003url\030\002 \002(\t\0227\n\021code_repositories\030\003 \003(\013" +
      "2\034.sizzle.types.CodeRepository\0225\n\020bug_re" +
      "positories\030\004 \003(\0132\033.sizzle.types.BugRepos" +
      "itory"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sizzle_types_Project_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sizzle_types_Project_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sizzle_types_Project_descriptor,
              new java.lang.String[] { "Name", "Url", "CodeRepositories", "BugRepositories", },
              sizzle.types.Toplevel.Project.class,
              sizzle.types.Toplevel.Project.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          sizzle.types.Code.getDescriptor(),
          sizzle.types.Bugs.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
